### PR TITLE
Myconicbridge

### PR DESCRIPTION
**Pull request by emreyamangil**
This update makes ConicNonlinearBridge ready for Pajarito.

### CODE REVIEW

**Comment by mlubin** [comment]
Something happened but this isn't a clean PR: "This branch has conflicts that must be resolved"

Please rebase onto master.

**Comment by mlubin** [comment]
Now there are 13 commits, could you merge them into one?

**Comment by emreyamangil** [comment]
git rebase is dying on me for some reason :( Btw I just realized some of these are your commits, how did this happen?? Do you want me to start a clean PR?

**Comment by mlubin** [comment]
Closed by #3

**Pull request closed without merging**
