### PR TITLE
Enable code coverage

### PR DESCRIPTION
**Pull request by mlubin**
@chriscoey

### CODE REVIEW

**Comment by mlubin** [comment]
I can't test this before #10 is merged because Julia 0.5 doesn't run anymore and Convex.jl doesn't have a tagged version that runs on 0.6.

**Comment by chriscoey** [comment]
#10 is ready and passing

**Comment by mlubin** [comment]
82% coverage CC @ccoffrin

**Comment by ccoffrin** [comment]
ha ha ha, working on the v0.7/v1.0 update shortly.

**Comment by ccoffrin** [comment]
@chriscoey, FYI `setwarmstart` seems to be the key feature that the tests are not yet capturing.

**Comment by chriscoey** [comment]
Lol i will try to test that too

**Pull request merged**
